### ISSUE TITLE
Not working against Hyper-V

### ISSUE THREAD

**Issue by EternalRift** [LazyAhora/Detect-VM-and-Hypervisor#1]
Cool tool but it does not correctly identify if I am using Hyper-V or not. While I do have Hyper-V enabled (but not a VM instance running), it still detects my host machine as a VM. Is there a way you can make it only detect Hyper-V if an actual instance of it is running?

**Comment by EternalRift** [comment]
Also, your discord ID does not work

**Comment by LazyAhora** [comment]
I don't do any test on Hyper-V,because i am using VMWare.
I google informathion about  Hyper-V and it's hypervisor type 1 or 1+(hybrid).I dont' think what we can ez check this from ring3.
Maybe you need change setting for prevent this detecthin(i don't know and just try use google).
